import { buildMentorInsights } from "./mentorInsights";

function formatList(items = []) {
	return items.length > 0 ? items.map(item => `- ${item}`).join("\n") : "- None recorded";
}

function formatCareerMatches(matches = []) {
	if (!matches.length) return "- No career matches available.";
	return matches
		.map(
			(match, index) =>
				`### ${index + 1}. ${match.career} (${match.score}%)\n- Matched: ${match.matchedSkills?.join(", ") || "None"}\n- Missing: ${match.missingSkills?.join(", ") || "None"}\n- Estimated effort: ~${match.estimatedWeeks || "N/A"} weeks`
		)
		.join("\n\n");
}

function formatRoadmap(roadmap = []) {
	if (!roadmap.length) return "- No roadmap generated.";
	return roadmap
		.map(
			phase =>
				`### ${phase.phase}: ${phase.title}\n${phase.items?.map(item => `- ${item}`).join("\n") || ""}\n*Outcome:* ${phase.outcome}`
		)
		.join("\n\n");
}

function formatStudyPlan(schedule = []) {
	if (!schedule.length) return "- No study plan generated.";
	return schedule
		.map(day => `- **${day.day}** (${day.hours}h): ${day.focus} — ${day.task}`)
		.join("\n");
}

function formatProjects(projects = {}) {
	const tiers = ["beginner", "intermediate", "advanced"];
	return tiers
		.map(tier => {
			const project = projects[tier];
			if (!project) return `### ${tier}\n- No recommendation`;
			return `### ${project.difficulty || tier}\n- **${project.title}** (${project.duration || "TBD"})\n- ${project.description}\n- Skills: ${project.skills?.join(", ") || "N/A"}`;
		})
		.join("\n\n");
}

export function generateCareerReportMarkdown(analysis = {}) {
	const profile = analysis.profile || {};
	const readiness = analysis.readiness || {};
	const skillGap = analysis.skillGap || {};
	const mentor = buildMentorInsights(analysis);

	return `# CareerCompass AI — Career Report

*Generated for ${profile.name || "Student"}*

---

## Profile

- **Name:** ${profile.name || "N/A"}
- **Degree:** ${profile.degree || "N/A"}
- **Career Goal:** ${profile.goal || "N/A"}
- **Study Hours/Day:** ${profile.hoursPerDay || "N/A"}
- **Skills:** ${profile.skills?.join(", ") || "N/A"}
- **Projects:** ${profile.projects?.join(", ") || "N/A"}

---

## Career Readiness Score

**${readiness.score ?? 0}%** — ${readiness.label || "N/A"}

### Strengths
${formatList(readiness.strengths)}

### Weaknesses
${formatList(readiness.weaknesses)}

---

## Skill Gaps

### Existing Skills
${formatList(skillGap.existingSkills)}

### Missing Skills
${formatList(skillGap.missingSkills)}

### Priority Skills
${formatList(skillGap.prioritySkills)}

---

## Career Matches

${formatCareerMatches(analysis.careerMatches)}

---

## AI Mentor Insights

${mentor.paragraphs.join("\n\n")}

---

## Learning Roadmap

${formatRoadmap(analysis.roadmap)}

---

## Weekly Study Plan

${formatStudyPlan(analysis.weeklySchedule)}

---

## Project Recommendations

${formatProjects(analysis.projectRecommendations)}

---

*Report generated by CareerCompass AI — Your Personal AI Career Mentor*
`;
}

export function downloadMarkdownReport(analysis = {}) {
	const content = generateCareerReportMarkdown(analysis);
	const name = analysis.profile?.name?.replace(/\s+/g, "-").toLowerCase() || "student";
	const filename = `careercompass-report-${name}-${Date.now()}.md`;
	const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = filename;
	document.body.appendChild(link);
	link.click();
	document.body.removeChild(link);
	URL.revokeObjectURL(url);
}
