import Button from "../ui/Button";

export default function Hero() {
	return (
		<section className="relative overflow-hidden rounded-[40px] border border-white/5 bg-gradient-to-b from-white/5 to-transparent p-8 shadow-[0_30px_80px_rgba(3,7,18,0.4)] backdrop-blur sm:p-12 lg:p-16">
			<div className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full bg-cyan-500/10 blur-3xl animate-pulse-slow" />
			<div className="pointer-events-none absolute -bottom-20 -left-20 h-72 w-72 rounded-full bg-blue-500/10 blur-3xl animate-pulse-slow" />

			<div className="relative max-w-3xl animate-fade-in">
				<p className="text-xs font-semibold uppercase tracking-[0.32em] text-cyan-400 font-display">
					Your Personal AI Career Mentor
				</p>
				<h1 className="mt-4 font-display text-4xl font-extrabold tracking-tight text-white sm:text-5xl lg:text-6xl leading-[1.1] text-wrap:balance">
					CareerCompass AI
				</h1>
				<p className="mt-5 font-display text-lg text-cyan-100/90 font-medium sm:text-xl leading-relaxed">
					Discover your ideal career path, close skill gaps, and build a personalized roadmap for success.
				</p>
				<p className="mt-4 max-w-2xl text-base leading-relaxed text-slate-400">
					Analyze your skill sets, evaluate project portfolio readiness, and receive guidance generated by AI. Empower your learning journey with target milestones.
				</p>
				<div className="mt-8 flex flex-col gap-3.5 sm:flex-row">
					<Button href="/assessment" variant="primary" className="h-12 px-8">
						Start Assessment
					</Button>
					<Button href="#features" variant="secondary" className="h-12 px-8">
						Explore Features
					</Button>
				</div>
			</div>
		</section>
	);
}
